### ISSUE TITLE
OFF TOPIC

### ISSUE THREAD

**Issue by romrp** [luni64/TeensyStep#98]
Sorry to comment here, I found nowhere else to post. Where do I learn more about steppers? I fail to understand how the same driver is slower in an Arduino Mega for an instance. Please point me in the right direction. Thank you.

**Comment by luni64** [comment]
A stepper is always exactly as fast as you pulse it (unless you pulse too fast). The problem is that, especially with microstepping, you need a fairly high pulse rate which requires a fast processor. For the Mega, the best lib I'm aware of is the AccelStepper. But this is limited to some 5-10kHz (IIRC). At say 5kHz, 1/16 microstepping and 200 full steps per rev you get 5kHz / 200 / 16 = 1.56 rev/sec = 93rpm which is not very fast. 
Teensystep can pulse the motor up to 300kHz. The net is full of information about steppers. Google is your friend. The TeenesyStep homepage also has some info about steppers and drivers: https://luni64.github.io/TeensyStep/applications/
